app:
  listen:
    host: 0.0.0.0
    port: 8000
  logging:
    version: 1
    disable_existing_loggers: false
    formatters:
      sensorkit-monitor:
        format: '%(levelname)s %(asctime)s : %(message)s'
    handlers:
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: sensorkit-monitor
        filename: /tmp/sensorkit-monitor.log
        maxBytes: 1048576
        backupCount: 2
    root:
      level: DEBUG
      handlers: [file]
  metrics:
    encoding: prometheus
    labels:
      room: office
      version: 0.0.1
sensorkit:
  env:
    indoors: true
  virtual-devices:
    static-altitude:
      type: meter
      module: .virtuals.static
      builder: StaticBuilder
      capabilities:
        - altitude
      args:
        values:
          altitude:
            value: 1688
            units: m
    open-meteo-current:
      type: meter
      module: .virtuals.openmeteo
      builder: OpenMeteoCurrentBuilder
      capabilities:
        #- temperature
        #- relative_humidity
        #- rain
        #- showers
        - pressure_msl
        - temperature
        - relative_humidity
      args:
        interval: PT1M
        params:
          longitude: -105.1230315
          latitude: 39.7592537
          timezone: America/Denver
  calibrations:
    bmp390:
      - measurement: pressure_msl
        target:
          property: sea_level_pressure
          where: real # or on the object interface 'abstract'
        source:
          virtual: open-meteo-current
        policy:
          aggregation: average
          interval: PT1M
    scd41:
      - measurement: altitude
        target:
          property: altitude
          where: real
        source:
          virtual: static-altitude
        policy:
          aggregation: first
          interval: oneshot
      - measurement: pressure
        target:
          method: set_ambient_pressure
          where: real
        source:
          meter: bmp390
        policy:
          aggregation: average
          type: int
          interval: PT1M
